CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    ProfilePicture VARCHAR(255),
    Bio TEXT,
    JoinDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastActive DATETIME
);

CREATE TABLE Friendships (
    FriendshipID INT AUTO_INCREMENT PRIMARY KEY,
    UserID1 INT NOT NULL,
    UserID2 INT NOT NULL,
    Status ENUM('pending', 'accepted') NOT NULL,
    InitiatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID1) REFERENCES Users(UserID),
    FOREIGN KEY (UserID2) REFERENCES Users(UserID)
);

CREATE TABLE Locations (
    LocationID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Latitude DECIMAL(10, 8) NOT NULL,
    Longitude DECIMAL(11, 8) NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Meetups (
    MeetupID INT AUTO_INCREMENT PRIMARY KEY,
    Participants TEXT NOT NULL,
    MeetupLocation VARCHAR(255) NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    Status ENUM('planned', 'ongoing', 'completed') NOT NULL
);

CREATE TABLE Ratings (
    RatingID INT AUTO_INCREMENT PRIMARY KEY,
    MeetupID INT NOT NULL,
    RatedUserID INT NOT NULL,
    RatingUserID INT NOT NULL,
    Score INT NOT NULL,
    Comment TEXT,
    FOREIGN KEY (MeetupID) REFERENCES Meetups(MeetupID),
    FOREIGN KEY (RatedUserID) REFERENCES Users(UserID),
    FOREIGN KEY (RatingUserID) REFERENCES Users(UserID)
);
